# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2f8d7cce1af46da2a3bed76b290324a902afaee3a0efd3012d9128e619fa759e513b6b790b9e5edf3aecddb6301b699810671e4886e9d738d8655f0c556708e9

test:
  secret_key_base: ae5161e564117640f74bc2f4104e34eb5f4966543b4a451decdd8b6f46ce8ea80fa87f755d7c7e78a5ae51e448993adcd7b2c26bce0032bd7076e852c1512ec4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
